name: boomflame
description: 
  Boomflame brings simple and extensible animations to Flame!
  Bring your animations to life right away!
version: 1.0.8
homepage: https://github.com/TheMaverickProgrammer/boomflame

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  meta: ^1.12.0
  vector_math: ^2.1.4
  flame: ^1.32.0
  boomsheets: ^1.0.11

dev_dependencies:
  flutter_lints: ^6.0.0
