name: boomflame
description: 
  Boomflame brings simple and extendable animations to Flame!
  Bring your animations to life right away!
version: 1.0.2
homepage: https://github.com/TheMaverickProgrammer/boomflame

environment:
  sdk: '^3.3.4'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  boomsheets: ^1.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
