name: boomflame
description: 
  Boomflame combines the convenience of Boomsheets with the power of Flame engine!
  Bring your animations to life using the boomflame AnimationComponent right away!
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.17.0
  boomsheets: ^1.0.3
  flame_tiled: ^1.20.2
  flame_audio: ^2.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/anims/
    - assets/images/
    - assets/images/tiles/
    - assets/maps/
    - assets/audio/